name: SeedAudit CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  seedaudit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt || true

      - name: Run SeedAudit Scanner
        run: |
          python -m seedaudit.cli scan ./ --out report.json --fail-on-severity critical

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: seedaudit-report
          path: report.json
